#!/bin/bash

FILE="data.json"

# استخدام jq + awk + sed لاستخراج البيانات
NAME=$(jq -r '.name' $FILE | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
formatted_height=$(jq -r '.height' $FILE | awk '{print $1}')
formatted_weight=$(jq -r '.weight' $FILE | awk '{print $1}')
TYPE=$(jq -r '.types[0].type.name' $FILE | sed 's/.*/\u&/')

# الصياغة المطلوبة من الشيك
echo "$NAME is of type $TYPE, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
