#!/bin/bash

FILE="data.json"

# استخراج البيانات
NAME=$(jq -r '.name' $FILE | sed 's/.*/\u&/')  # Capitalize first letter
HEIGHT=$(jq -r '.height' $FILE)
WEIGHT=$(jq -r '.weight' $FILE)
TYPE=$(jq -r '.types[0].type.name' $FILE | sed 's/.*/\u&/')  # Capitalize first letter

# تنسيق الإخراج
echo "$NAME is of type $TYPE, weighs ${WEIGHT}kg, and is ${HEIGHT}m tall."
